/**
 * Generates seed.sql from the same demo data DataSeeder.java / ProductService.java
 * (initializeProducts) used to seed on Java service startup. Run with:
 *   npx tsx scripts/seed-generate.ts > seed.sql
 * then apply with:
 *   npx wrangler d1 execute digibank --local  --file=./seed.sql
 *   npx wrangler d1 execute digibank --remote --file=./seed.sql
 */

function sqlStr(v: string | null): string {
  if (v === null) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function nowIso() {
  return new Date().toISOString();
}

// Standard amortization formula, matching ProductService.calculateRepayment:
// M = P * r * (1+r)^n / ((1+r)^n - 1), r = annualRatePercent / 1200
function monthlyRepayment(annualRatePercent: number, principal: number, termMonths: number): number {
  const r = annualRatePercent / 1200;
  const factor = Math.pow(1 + r, termMonths);
  return Math.round(((principal * r * factor) / (factor - 1)) * 100) / 100;
}

const lines: string[] = [];
lines.push("-- Generated by scripts/seed-generate.ts — do not edit by hand, edit the script instead.");

// --- Seeded staff accounts (auth-service DataSeeder.run) ---
type SeedUser = { email: string; nationalId: string; fullName: string; role: string };
const staffUsers: SeedUser[] = [
  { email: "underwriter@digibank.com", nationalId: "000000014", fullName: "DigiBank Underwriter", role: "UNDERWRITER" },
  { email: "admin@digibank.com", nationalId: "000000015", fullName: "DigiBank Admin", role: "ADMIN" },
  { email: "banker@digibank.com", nationalId: "000000027", fullName: "DigiBank Banker", role: "BANKER" },
];
for (const u of staffUsers) {
  lines.push(
    `INSERT INTO users (uuid, email, national_id, id_issue_date, full_name, role, created_at, enabled, email_verified, otp_attempts)
     SELECT lower(hex(randomblob(16))), ${sqlStr(u.email)}, ${sqlStr(u.nationalId)}, '2015-01-01', ${sqlStr(u.fullName)}, ${sqlStr(u.role)}, '${nowIso()}', 1, 1, 0
     WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = ${sqlStr(u.email)});`
  );
}

// --- FAQs (auth-service DataSeeder.seedFaqs) ---
type SeedFaq = {
  category: string; question: string; answer: string;
  questionHe: string; answerHe: string;
  videoId: string | null; order: number;
};
const faqs: SeedFaq[] = [
  { category: "Loan Eligibility", question: "Who is eligible to apply for a DigiBank personal loan?", answer: "To be eligible you must be an Israeli resident aged 18 or over, with a valid Teudat Zehut (National ID), a monthly gross income of at least ₪8,000, and a credit score of 580 or above. Additional criteria may apply based on the product selected.",
    questionHe: "מי זכאי להגיש בקשה להלוואה פרטית מדיגילנד?", answerHe: "כדי להיות זכאים עליכם להיות תושבי ישראל בני 18 ומעלה, בעלי תעודת זהות בתוקף, הכנסה חודשית ברוטו של ₪8,000 לפחות, וציון אשראי של 580 ומעלה. ייתכנו קריטריונים נוספים בהתאם למוצר שנבחר.", videoId: null, order: 1 },
  { category: "Loan Eligibility", question: "Can I apply if I am self-employed?", answer: "Yes. Self-employed applicants are welcome. You will need to provide your most recent two years of income tax assessments (Shuma) and bank statements showing regular income deposits.",
    questionHe: "האם אני יכול/ה להגיש בקשה אם אני עצמאי/ת?", answerHe: "כן. עצמאים מוזמנים להגיש בקשה. יהיה עליכם לספק שומות מס הכנסה משתי השנים האחרונות ודפי חשבון בנק המראים הפקדות הכנסה סדירות.", videoId: "placeholder", order: 2 },
  { category: "Loan Eligibility", question: "What is the minimum and maximum loan amount?", answer: "Our personal loan range is ₪5,000 to ₪300,000, subject to affordability assessment and the specific product you qualify for.",
    questionHe: "מהו סכום ההלוואה המינימלי והמקסימלי?", answerHe: "טווח ההלוואות הפרטיות שלנו הוא בין ₪5,000 ל-₪300,000, בכפוף לבדיקת יכולת החזר ולמוצר הספציפי שאתם זכאים לו.", videoId: null, order: 3 },
  { category: "Application Process", question: "How long does the application take to complete?", answer: "The online application typically takes 10–15 minutes to complete. Once submitted, an automated affordability assessment is performed instantly. A conditional decision is usually available within minutes.",
    questionHe: "כמה זמן לוקח למלא את הבקשה?", answerHe: "מילוי הבקשה המקוונת אורך בדרך כלל 10–15 דקות. לאחר השליחה, מתבצעת בדיקת יכולת החזר אוטומטית מיידית. החלטה מותנית זמינה בדרך כלל תוך דקות.", videoId: "placeholder", order: 1 },
  { category: "Application Process", question: "What documents will I need?", answer: "You will need: a valid Teudat Zehut (National ID), proof of income (recent payslips or Shuma for self-employed), recent bank statements (last 3 months), and proof of address (utility bill or bank statement).",
    questionHe: "אילו מסמכים אצטרך?", answerHe: "תזדקקו ל: תעודת זהות בתוקף, אישור הכנסה (תלושי שכר אחרונים או שומה לעצמאים), דפי חשבון בנק אחרונים (3 חודשים אחרונים), ואישור כתובת (חשבון חברת שירותים או דף בנק).", videoId: null, order: 2 },
  { category: "Application Process", question: "Can I save my application and return to it later?", answer: "Yes. DigiBank's portal automatically saves your progress at every step. Simply log back in and your application will resume exactly where you left off.",
    questionHe: "האם אפשר לשמור את הבקשה ולחזור אליה מאוחר יותר?", answerHe: "כן. פורטל דיגילנד שומר אוטומטית את ההתקדמות שלכם בכל שלב. פשוט התחברו מחדש והבקשה תמשיך בדיוק מהמקום שבו הפסקתם.", videoId: null, order: 3 },
  { category: "Application Process", question: "What happens after I submit my application?", answer: "Your application goes through an automated affordability assessment. If successful, you will be shown eligible loan products. Once you select a product, a conditional approval is issued and your loan agreement documents are generated automatically.",
    questionHe: "מה קורה אחרי שאני שולח/ת את הבקשה?", answerHe: "הבקשה שלכם עוברת בדיקת יכולת החזר אוטומטית. במקרה של הצלחה, יוצגו לכם מוצרי הלוואה מתאימים. לאחר בחירת מוצר, מונפק אישור מותנה ומסמכי הסכם ההלוואה נוצרים אוטומטית.", videoId: "placeholder", order: 4 },
  { category: "Interest Rates & Repayments", question: "What interest rates does DigiBank offer?", answer: "Our personal loan rates start from 4.8% APR for qualifying customers. The rate offered to you will depend on your credit profile, loan amount, term, and the product selected. Your personalised rate will be shown before you accept any offer.",
    questionHe: "אילו ריביות מציעה דיגילנד?", answerHe: "ריביות ההלוואות הפרטיות שלנו מתחילות מ-4.8% ריבית שנתית ללקוחות זכאים. הריבית המוצעת לכם תלויה בפרופיל האשראי, בסכום ההלוואה, בתקופה ובמוצר שנבחר. הריבית האישית תוצג לפני אישור כל הצעה.", videoId: null, order: 1 },
  { category: "Interest Rates & Repayments", question: "How is my monthly repayment calculated?", answer: "Monthly repayments are calculated using the standard amortisation formula, dividing the loan principal equally over the term with interest. Your repayment schedule will be provided in your loan agreement documentation.",
    questionHe: "כיצד מחושב ההחזר החודשי שלי?", answerHe: "ההחזרים החודשיים מחושבים לפי נוסחת הפחתה סטנדרטית, המחלקת את קרן ההלוואה באופן שווה לאורך התקופה בתוספת ריבית. לוח הסילוקין יימסר לכם במסמכי הסכם ההלוואה.", videoId: "placeholder", order: 2 },
  { category: "Interest Rates & Repayments", question: "Can I make early repayments?", answer: "Yes. DigiBank allows early partial or full repayments. Early settlement fees may apply — please refer to your loan agreement or speak to your advisor for specific terms.",
    questionHe: "האם אפשר לבצע פירעון מוקדם?", answerHe: "כן. דיגילנד מאפשרת פירעון מוקדם חלקי או מלא. ייתכנו עמלות פירעון מוקדם — עיינו בהסכם ההלוואה או פנו ליועץ שלכם לפרטים.", videoId: null, order: 3 },
  { category: "Interest Rates & Repayments", question: "On which date will my repayments be taken?", answer: "You can choose your preferred monthly repayment date during the application (1st–28th of the month). Repayments are collected via direct debit from your nominated bank account.",
    questionHe: "באיזה תאריך ייגבו ההחזרים שלי?", answerHe: "תוכלו לבחור את תאריך ההחזר החודשי המועדף עליכם במהלך הבקשה (בין ה-1 ל-28 בחודש). ההחזרים נגבים בהוראת קבע מחשבון הבנק שציינתם.", videoId: null, order: 4 },
  { category: "Credit & Affordability", question: "Will applying affect my credit score?", answer: "The initial application performs a soft credit search, which does not affect your credit score. A full credit search will only be performed when you accept a conditional offer, as disclosed in the credit consent declaration.",
    questionHe: "האם הגשת הבקשה תשפיע על ציון האשראי שלי?", answerHe: "הבקשה הראשונית מבצעת בדיקת אשראי רכה שאינה משפיעה על ציון האשראי שלכם. בדיקת אשראי מלאה תתבצע רק כאשר תאשרו הצעה מותנית, כפי שמפורט בהצהרת הסכמת האשראי.", videoId: null, order: 1 },
  { category: "Credit & Affordability", question: "What is the Debt-to-Income (DTI) ratio?", answer: "Your DTI ratio compares your total monthly debt obligations to your gross monthly income. DigiBank's lending policy requires a DTI ratio of 40% or below. A lower DTI demonstrates stronger repayment capacity.",
    questionHe: "מהו יחס החוב להכנסה (DTI)?", answerHe: "יחס ה-DTI משווה בין סך ההתחייבויות החודשיות שלכם להכנסה החודשית ברוטו. מדיניות האשראי של דיגילנד דורשת יחס DTI של 40% ומטה. יחס נמוך יותר מעיד על יכולת החזר חזקה יותר.", videoId: null, order: 2 },
  { category: "Credit & Affordability", question: "My affordability assessment did not pass — what can I do?", answer: "If your automated assessment does not pass, please contact your DigiBank advisor for a manual review. Changes in circumstances, additional income documentation, or a reduced loan amount may result in a different outcome.",
    questionHe: "בדיקת יכולת ההחזר שלי לא עברה — מה אפשר לעשות?", answerHe: "אם הבדיקה האוטומטית לא עברה, פנו ליועץ דיגילנד שלכם לבדיקה ידנית. שינויים בנסיבות, מסמכי הכנסה נוספים, או הקטנת סכום ההלוואה עשויים להוביל לתוצאה שונה.", videoId: null, order: 3 },
  { category: "Security & Privacy", question: "How does DigiBank protect my personal data?", answer: "All data is encrypted in transit using TLS 1.3 and at rest using AES-256 encryption. DigiBank complies fully with Israeli Privacy Protection Law 5741-1981 and GDPR-equivalent standards.",
    questionHe: "כיצד דיגילנד מגנה על המידע האישי שלי?", answerHe: "כל המידע מוצפן בהעברה באמצעות TLS 1.3 ובאחסון באמצעות הצפנת AES-256. דיגילנד פועלת בהתאם לחוק הגנת הפרטיות התשמ\"א-1981 ולתקנים מקבילים ל-GDPR.", videoId: null, order: 1 },
  { category: "Security & Privacy", question: "Who can see my application information?", answer: "Only authorised DigiBank personnel directly involved in the processing of your application can access your data. Data is never sold or shared with third parties for marketing purposes.",
    questionHe: "מי יכול לראות את פרטי הבקשה שלי?", answerHe: "רק אנשי צוות מורשים בדיגילנד המעורבים ישירות בטיפול בבקשה שלכם יכולים לגשת למידע שלכם. המידע לעולם לא נמכר ואינו משותף עם צדדים שלישיים לצרכי שיווק.", videoId: null, order: 2 },
];
for (const f of faqs) {
  lines.push(
    `INSERT INTO faqs (category, question, answer, question_he, answer_he, video_id, display_order)
     SELECT ${sqlStr(f.category)}, ${sqlStr(f.question)}, ${sqlStr(f.answer)}, ${sqlStr(f.questionHe)}, ${sqlStr(f.answerHe)}, ${sqlStr(f.videoId)}, ${f.order}
     WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE question = ${sqlStr(f.question)});`
  );
}

// --- Loan products (product-service ProductService.initializeProducts) ---
type SeedProduct = {
  code: string; name: string; description: string; rate: number; min: number; max: number;
  minTerm: number; maxTerm: number; minScore: number; minIncome: number; maxDti: number;
  risk: string; type: "PERSONAL" | "BUSINESS";
};
const products: SeedProduct[] = [
  { code: "SL001", name: "Standard Personal Loan", description: "Our flexible standard loan for a wide range of personal needs including home improvements, weddings, travel, and more.", rate: 5.5, min: 10000, max: 150000, minTerm: 12, maxTerm: 84, minScore: 6, minIncome: 8000, maxDti: 40, risk: "LOW,MEDIUM,HIGH", type: "PERSONAL" },
  { code: "PL001", name: "Premium Personal Loan", description: "Exclusive premium rates for customers with excellent financial profiles. Ideal for larger purchases or debt consolidation.", rate: 4.8, min: 50000, max: 300000, minTerm: 24, maxTerm: 60, minScore: 7, minIncome: 15000, maxDti: 35, risk: "LOW,MEDIUM", type: "PERSONAL" },
  { code: "EL001", name: "Express Loan", description: "Fast-tracked approval for smaller amounts with minimal documentation. Funds typically available within 24 hours.", rate: 6.2, min: 5000, max: 50000, minTerm: 6, maxTerm: 36, minScore: 5, minIncome: 6000, maxDti: 45, risk: "LOW,MEDIUM,HIGH", type: "PERSONAL" },
  { code: "BTL001", name: "Business Term Loan", description: "A lump-sum loan for established businesses to fund expansion, equipment, or major one-off investments, repaid over a fixed term.", rate: 7.0, min: 50000, max: 1000000, minTerm: 12, maxTerm: 84, minScore: 6, minIncome: 0, maxDti: 100, risk: "LOW,MEDIUM,HIGH", type: "BUSINESS" },
  { code: "WCL001", name: "Working Capital Line", description: "Short-term financing to cover day-to-day operating expenses, payroll, and inventory while awaiting receivables.", rate: 8.2, min: 20000, max: 400000, minTerm: 6, maxTerm: 36, minScore: 6, minIncome: 0, maxDti: 100, risk: "LOW,MEDIUM,HIGH", type: "BUSINESS" },
  { code: "EQF001", name: "Equipment Finance Loan", description: "Finance for purchasing machinery, vehicles, or other business equipment, secured against the asset itself.", rate: 6.5, min: 30000, max: 600000, minTerm: 12, maxTerm: 60, minScore: 7, minIncome: 0, maxDti: 100, risk: "LOW,MEDIUM", type: "BUSINESS" },
];
for (const p of products) {
  lines.push(
    `INSERT INTO loan_products (product_code, product_name, description, annual_interest_rate, min_amount, max_amount, min_term_months, max_term_months, min_credit_score, min_monthly_income, max_dti, risk_categories, active, product_type)
     SELECT ${sqlStr(p.code)}, ${sqlStr(p.name)}, ${sqlStr(p.description)}, ${p.rate}, ${p.min}, ${p.max}, ${p.minTerm}, ${p.maxTerm}, ${p.minScore}, ${p.minIncome}, ${p.maxDti}, ${sqlStr(p.risk)}, 1, ${sqlStr(p.type)}
     WHERE NOT EXISTS (SELECT 1 FROM loan_products WHERE product_code = ${sqlStr(p.code)});`
  );
}

// --- Pre-approved offers (product-service ProductService.seedPreApprovedOffers) ---
type SeedOffer = { nationalId: string; productCode: string; productName: string; rate: number; amount: number; term: number };
const offers: SeedOffer[] = [
  { nationalId: "000000050", productCode: "PL001", productName: "Premium Personal Loan", rate: 4.8, amount: 120000, term: 60 },
  { nationalId: "000000051", productCode: "SL001", productName: "Standard Personal Loan", rate: 5.5, amount: 65000, term: 48 },
  { nationalId: "000000052", productCode: "EL001", productName: "Express Loan", rate: 6.2, amount: 25000, term: 24 },
];
for (const o of offers) {
  const repay = monthlyRepayment(o.rate, o.amount, o.term);
  const total = Math.round(repay * o.term * 100) / 100;
  lines.push(
    `INSERT INTO pre_approved_offers (national_id, product_code, product_name, annual_interest_rate, amount, term_months, monthly_repayment, total_repayable, consumed, created_at)
     SELECT ${sqlStr(o.nationalId)}, ${sqlStr(o.productCode)}, ${sqlStr(o.productName)}, ${o.rate}, ${o.amount}, ${o.term}, ${repay}, ${total}, 0, '${nowIso()}'
     WHERE NOT EXISTS (SELECT 1 FROM pre_approved_offers WHERE national_id = ${sqlStr(o.nationalId)});`
  );
}

// --- Default rules rows (were in-memory Spring beans; now single-row D1 tables) ---
lines.push(
  `INSERT INTO affordability_rules (id, max_dti, max_hti, min_monthly_income, base_annual_rate, repayment_capacity_factor, min_credit_score, auto_approval_threshold_single, auto_approval_threshold_joint)
   SELECT 1, 40, 35, 8000, 0.06, 0.40, 5, 30000, 50000
   WHERE NOT EXISTS (SELECT 1 FROM affordability_rules WHERE id = 1);`
);
lines.push(
  `INSERT INTO mandate_rules (id, underwriter_limit, senior_underwriter_limit, head_of_lending_limit, coo_limit, ceo_limit)
   SELECT 1, 100000, 300000, 750000, 2000000, 999999999
   WHERE NOT EXISTS (SELECT 1 FROM mandate_rules WHERE id = 1);`
);
lines.push(
  `INSERT INTO branding_settings (id, primary_color, accent_color, logo_url)
   SELECT 1, '#003366', '#FBB034', NULL
   WHERE NOT EXISTS (SELECT 1 FROM branding_settings WHERE id = 1);`
);

console.log(lines.join("\n\n"));
