import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { GeneratedDocument, UploadedDocument } from '../models';
import { API_BASE } from './api-base';

const API = `${API_BASE}/api/documents`;

function filenameFrom(res: HttpResponse<Blob>, fallback: string): string {
  const disposition = res.headers.get('Content-Disposition') ?? '';
  const match = /filename="?([^"]+)"?/.exec(disposition);
  return match ? match[1] : fallback;
}

@Injectable({ providedIn: 'root' })
export class DocumentService {
  constructor(private http: HttpClient) {}

  // Returns every document in the offer pack generated by this call (cover letter, Key Facts
  // Statement, Repayment Schedule, and — at the conditional stage only — Terms & Conditions), not
  // just the one document type requested.
  generate(request: any): Observable<GeneratedDocument[]> {
    return this.http.post<GeneratedDocument[]>(`${API}/generate`, request);
  }

  getGenerated(customerId: number): Observable<GeneratedDocument[]> {
    return this.http.get<GeneratedDocument[]>(`${API}/customer/${customerId}`);
  }

  getByApplication(appRef: string): Observable<GeneratedDocument[]> {
    return this.http.get<GeneratedDocument[]>(`${API}/application/${appRef}`);
  }

  getUploaded(appRef: string): Observable<UploadedDocument[]> {
    return this.http.get<UploadedDocument[]>(`${API}/uploaded/${appRef}`);
  }

  upload(appRef: string, customerId: number, file: File, docType = 'SUPPORTING'): Observable<any> {
    const form = new FormData();
    form.append('file', file);
    form.append('applicationRef', appRef);
    form.append('customerId', String(customerId));
    form.append('documentType', docType);
    return this.http.post<any>(`${API}/upload`, form);
  }

  // File downloads/views used to be plain `window.open(url)` — a bare browser navigation, which
  // can't carry the Authorization header these endpoints require now that /api/documents/* is
  // authenticated. Fetching as a blob through HttpClient (so the auth interceptor attaches the
  // token) and triggering the save/open client-side keeps the same fire-and-forget call shape for
  // every existing caller.
  private saveBlob(res: HttpResponse<Blob>, fallbackName: string): void {
    const blob = res.body;
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filenameFrom(res, fallbackName);
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  // Popups opened asynchronously (i.e. after the HTTP response resolves) fall outside the user
  // gesture that triggered the click, so browsers silently block them. Opening a blank window
  // synchronously in the click handler and redirecting it once the blob arrives keeps it tied to
  // the gesture.
  private openBlob(res: HttpResponse<Blob>, win: Window | null): void {
    const blob = res.body;
    if (!blob || !win) return;
    const url = URL.createObjectURL(blob);
    win.location.href = url;
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  }

  download(docId: string | number): void {
    this.http.get(`${API}/${docId}/download`, { responseType: 'blob', observe: 'response' })
      .subscribe({ next: res => this.saveBlob(res, `document-${docId}.pdf`) });
  }

  view(docId: string | number): void {
    const win = window.open('', '_blank');
    this.http.get(`${API}/${docId}/view`, { responseType: 'blob', observe: 'response' })
      .subscribe({ next: res => this.openBlob(res, win), error: () => win?.close() });
  }

  downloadUploaded(id: string | number): void {
    this.http.get(`${API}/uploaded/file/${id}/download`, { responseType: 'blob', observe: 'response' })
      .subscribe({ next: res => this.saveBlob(res, `document-${id}`) });
  }

  viewUploaded(id: string | number): void {
    const win = window.open('', '_blank');
    this.http.get(`${API}/uploaded/file/${id}/view`, { responseType: 'blob', observe: 'response' })
      .subscribe({ next: res => this.openBlob(res, win), error: () => win?.close() });
  }
}
